version: '3'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "9091:8081"  # Maps host port 9091 to container port 8081
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devsecops

volumes:
  nexus_data:

networks:
  devsecops:
    driver: bridge

