version: '3.8'

services:
  dependency-track:
    image: dependencytrack/bundled:latest
    container_name: dependency-track
    ports:
      - "9090:8080"  # Maps host port 9090 to container port 8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/dependencytrack
      - DATABASE_USER=dependencytrack
      - DATABASE_PASSWORD=dependencytrack
    volumes:
      - dependencytrack_data:/opt/dependency-track/data
    networks:
      - devsecops
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: dependencytrack_db
    environment:
      - POSTGRES_USER=dependencytrack
      - POSTGRES_PASSWORD=dependencytrack
      - POSTGRES_DB=dependencytrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devsecops

networks:
  devsecops:
    driver: bridge

volumes:
  dependencytrack_data:
  postgres_data:

