version: '3.8'

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9001:9000"  
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - devsecops

networks:
  devsecops:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:

