version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9001:9000"  # Maps host port 9001 to container port 9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - devsecops

networks:
  devsecops:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:

