version: '3'

services:
  trivy:
    image: aquasec/trivy:latest
    container_name: trivy
    entrypoint: ["trivy"]
    volumes:
      - trivy_cache:/root/.cache/trivy
    networks:
      - devsecops
    # Optional: You can add environment variables or command options here
    environment:
      - TRIVY_CACHE_DIR=/root/.cache/trivy
    command: ["--help"]  # Use this to see available commands; replace with actual scan command

volumes:
  trivy_cache:

networks:
  devsecops:
    driver: bridge


