version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - devsecops

  logstash:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - logstash_config:/usr/share/logstash/config
      - logstash_pipelines:/usr/share/logstash/pipeline
    networks:
      - devsecops

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - devsecops

volumes:
  elasticsearch_data:
  logstash_config:
  logstash_pipelines:
  kibana_data:

networks:
  devsecops:
    driver: bridge

