version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme  # Password for the elastic user
      - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.logstash.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.0
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: >
      /bin/sh -c "
        echo 'input { beats { port => 5044 } }' > /usr/share/logstash/pipeline/logstash.conf && 
        echo 'output { elasticsearch { hosts => [\"http://elasticsearch:9200\"] user => \"elastic\" password => \"changeme\" index => \"logstash-%{[agent.version]}-%{+YYYY.MM.dd}\" } }' >> /usr/share/logstash/pipeline/logstash.conf &&
        bin/logstash -f /usr/share/logstash/pipeline/logstash.conf
      "

networks:
  elastic:
    driver: bridge

