version: '3'

services:
  owasp-zap:
    image: zaproxy/zap-stable:2.15.0
    container_name: owasp-zap
    ports:
      - "9090:8080"  # Map host port 9090 to container port 8080
    networks:
      - devsecops
    environment:
      - ZAP_USER=user
      - ZAP_PASSWORD=password
    volumes:
      - zap_data:/zap/wrk  # Optional: persist ZAP data

networks:
  devsecops:
    driver: bridge

volumes:
  zap_data:

