version: '3'

services:
  owasp-zap:
    image: zaproxy/zap-stable
    container_name: owasp-zap
    ports:
      - "7070:8080"  # Change the host port to 7070, keeping the container port as 8080
    volumes:
      - zap_data:/zap/wrk
    networks:
      - devsecops

volumes:
  zap_data:

networks:
  devsecops:
    driver: bridge

